name: rubrix

channels:
  - anaconda
  - conda-forge
  - defaults
  - pytorch

dependencies:
  # Core stack
  - python<3.9
  - h5py
  - numpy
  - scipy
  - tensorflow-hub

  # CUDA stack
  # Comment this stack while creating environment for CPU.
  # cudnn==8.2.1
  # cudatoolkit==11.3.1

  # CV Packages
  - scikit-image

  # NLP Packages
  - nltk
  - spacy==3.1.0

  # Website
  - flask

  # Visualization stack
  - matplotlib
  - jupyter

  - pip
  - pip:
     - tensorflow==2.5.0
     - opencv-python
     - kaggle
     - scikit-learn
